# Generated by CMake 2.8.7

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target mqueue
ADD_LIBRARY(mqueue SHARED IMPORTED)

# Create imported target queue_processes
ADD_EXECUTABLE(queue_processes IMPORTED)

# Import target "mqueue" for configuration ""
SET_PROPERTY(TARGET mqueue APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(mqueue PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "/home/chatsiri/workspacecpp/techniquecpp/pthread_queue/src/mqueue/libmqueue.so"
  IMPORTED_SONAME_NOCONFIG "libmqueue.so"
  )

# Import target "queue_processes" for configuration ""
SET_PROPERTY(TARGET queue_processes APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(queue_processes PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "/home/chatsiri/workspacecpp/techniquecpp/pthread_queue/src/queue_processes"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
